export const navItems = [
  ["Inicio", "inicio"],
  ["Experiencias", "experiencias"],
  ["Terapeutas", "terapeutas"],
  ["Musas Digitais", "musas"],
  ["Club Serenity", "club"],
  ["Conteudos", "conteudos"],
  ["Agendar", "agendar"],
];

export const discoveryTags = [
  "Elegante",
  "Romantica",
  "Confiante",
  "Misteriosa",
  "Natural",
  "Editorial",
  "Noturna",
  "Relaxante",
  "Intensa",
];

export const muses = [
  {
    name: "Clara",
    slug: "clara",
    age: "faixa adulta 30+",
    image: "/assets/clara-free-4.jpeg",
    avatar: "/assets/clara-perfil.png",
    phrase: "Solar, confiante e com uma presenca que combina naturalidade e misterio.",
    bio: "Clara mistura luz dourada, sorriso facil e uma atmosfera de descoberta sem pressa.",
    personality: "Confiante, espontanea, envolvente",
    aesthetic: "Luz dourada, editorial tropical, contraste suave",
    posts: "10 conteudos",
    latest: "4 fotos gratuitas - 6 fotos premium",
    price: "R$ 24,90/mes",
    tag: "Personagem digital criada por IA",
    freeImages: [
      "/assets/clara-free-1.jpeg",
      "/assets/clara-free-2.jpeg",
      "/assets/clara-free-3.jpeg",
      "/assets/clara-free-4.jpeg",
    ],
    premiumImages: [
      "/assets/clara-premium-1.jpeg",
      "/assets/clara-premium-2.jpeg",
      "/assets/clara-premium-3.jpeg",
      "/assets/clara-premium-4.jpeg",
      "/assets/clara-premium-5.jpeg",
      "/assets/clara-premium-6.jpeg",
    ],
  },
  {
    name: "Isabela",
    slug: "isabela",
    age: "faixa adulta 25+",
    image: "/assets/isabela-free-1.jpeg",
    avatar: "/assets/isabela-perfil.png",
    phrase: "Olhar calmo, presenca delicada e um charme que aparece sem esforco.",
    bio: "Isabela combina luz suave, curvas elegantes e uma intimidade visual mais proxima.",
    personality: "Delicada, curiosa, magnetica",
    aesthetic: "Quarto claro, tons vinho, pele natural e clima reservado",
    posts: "12 conteudos",
    latest: "4 fotos gratuitas - 8 fotos premium",
    price: "R$ 24,90/mes",
    tag: "Personagem digital criada por IA",
    freeImages: [
      "/assets/isabela-free-1.jpeg",
      "/assets/isabela-free-2.png",
      "/assets/isabela-free-3.jpeg",
      "/assets/isabela-free-4.jpeg",
    ],
    premiumImages: [
      "/assets/isabela-premium-1.jpeg",
      "/assets/isabela-premium-2.jpeg",
      "/assets/isabela-premium-3.jpeg",
      "/assets/isabela-premium-4.jpeg",
      "/assets/isabela-premium-5.jpeg",
      "/assets/isabela-premium-6.jpeg",
      "/assets/isabela-premium-7.jpeg",
      "/assets/isabela-premium-8.jpeg",
    ],
  },
  {
    name: "Patrícia",
    slug: "patricia",
    age: "faixa adulta 25+",
    image: "/assets/patricia-free-1.jpeg",
    avatar: "/assets/patricia-perfil.jpeg",
    phrase: "Doce no olhar, intensa nos detalhes e naturalmente envolvente.",
    bio: "Patrícia traz uma energia mais caseira e luminosa, com ensaios proximos, espelho e luz de fim de tarde.",
    personality: "Doce, direta, luminosa",
    aesthetic: "Luz quente, quarto claro, espelho e intimidade natural",
    posts: "5 conteudos",
    latest: "3 fotos gratuitas - 2 fotos premium",
    price: "R$ 24,90/mes",
    tag: "Personagem digital criada por IA",
    freeImages: [
      "/assets/patricia-free-1.jpeg",
      "/assets/patricia-free-2.jpeg",
      "/assets/patricia-free-3.jpeg",
    ],
    premiumImages: [
      "/assets/patricia-premium-1.jpeg",
      "/assets/patricia-premium-2.jpeg",
    ],
  },
  {
    name: "Luna",
    slug: "luna",
    age: "faixa adulta 28+",
    image: "/assets/serenity-feed-5.png",
    avatar: "/assets/serenity-feed-1.png",
    phrase: "Leveza, presenca e uma curiosidade silenciosa.",
    bio: "Perfil demonstrativo preparado para receber fotos reais da personagem.",
    personality: "Natural, calorosa, relaxante",
    aesthetic: "Spa, pele, respiro e tons claros",
    posts: "Conteudo pendente",
    latest: "Fotos reais pendentes de cadastro",
    price: "R$ 24,90/mes",
    tag: "Personagem digital criada por IA",
    freeImages: ["/assets/serenity-feed-5.png", "/assets/serenity-feed-1.png"],
    premiumImages: ["/assets/serenity-feed-3.png", "/assets/serenity-feed-4.png"],
  },
  {
    name: "Maya",
    slug: "maya",
    age: "faixa adulta 35+",
    image: "/assets/serenity-feed-3.png",
    avatar: "/assets/serenity-feed-2.png",
    phrase: "Confianca tranquila, sem pressa para revelar tudo.",
    bio: "Perfil demonstrativo preparado para receber fotos reais da personagem.",
    personality: "Confiante, editorial, intensa",
    aesthetic: "Grafite, champagne, sombras suaves",
    posts: "Conteudo pendente",
    latest: "Fotos reais pendentes de cadastro",
    price: "R$ 24,90/mes",
    tag: "Personagem digital criada por IA",
    freeImages: ["/assets/serenity-feed-3.png", "/assets/serenity-feed-2.png"],
    premiumImages: ["/assets/serenity-feed-4.png", "/assets/serenity-feed-5.png"],
  },
];

export const experiences = [
  {
    title: "Serenity Relax",
    duration: "60 ou 90 min",
    price: "sob consulta",
    copy: "Uma experiencia corporal para desacelerar, aliviar tensao e voltar para si.",
    benefits: ["Ambiente reservado", "Ritual sensorial", "Atendimento discreto"],
  },
  {
    title: "Jornada Serenity",
    duration: "90 min",
    price: "valor editavel",
    copy: "Um percurso mais completo para quem quer presenca, pausa e cuidado integral.",
    benefits: ["Recepcao tranquila", "Ritmo personalizado", "Pos-experiencia leve"],
  },
  {
    title: "Serenity a Dois",
    duration: "sob consulta",
    price: "mediante agenda",
    copy: "Uma proposta reservada para casais adultos que buscam conexao e bem-estar.",
    benefits: ["Privacidade", "Orientacao profissional", "Ritual compartilhado"],
  },
];

export const therapists = [
  ["Ana", "Terapias relaxantes", "Tardes e noites selecionadas"],
  ["Clara", "Ritual sensorial e respiracao", "Dias uteis"],
  ["Beatriz", "Cuidado corporal integrativo", "Agenda sob consulta"],
];

export const articles = [
  ["Sentidos", "Seu corpo tambem pede uma pausa", "Relaxamento nao e premio. E manutencao."],
  ["Intimidade", "Conexao sem pressa", "Como criar um tempo adulto, reservado e presente."],
  ["Bem-estar", "O luxo real e ter paz", "Rituais simples para sair do automatico."],
];
